name: build
on: pull_request

jobs:
  build:
    name: Build
    runs-on: [windows-latest]

    defaults:
      run:
        working-directory: ./app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Clean install
        run: npm ci
      - name: Build app
        run: npm run tauri build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: installers
          path: ./app/src-tauri/target/release/bundle/
